blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/kulturwunsch/Kultur-API-for-WP/discussions
    about: Please ask and answer questions here.
  - name: Report a security issue
    url: https://kulturwunsch.de/kontakt/
    about: Please report security vulnerabilities here.